/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeoIndexRouteImport } from './routes/geo.index'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as GeoCitationsRouteImport } from './routes/geo.citations'
import { Route as ContentIdRouteImport } from './routes/content.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoIndexRoute = GeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeoRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRoute,
} as any)
const GeoCitationsRoute = GeoCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => GeoRoute,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/content': typeof ContentRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/geo': typeof GeoRouteWithChildren
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/content/$id': typeof ContentIdRoute
  '/geo/citations': typeof GeoCitationsRoute
  '/content/': typeof ContentIndexRoute
  '/geo/': typeof GeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/credentials': typeof CredentialsRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/content/$id': typeof ContentIdRoute
  '/geo/citations': typeof GeoCitationsRoute
  '/content': typeof ContentIndexRoute
  '/geo': typeof GeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/content': typeof ContentRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/geo': typeof GeoRouteWithChildren
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/content/$id': typeof ContentIdRoute
  '/geo/citations': typeof GeoCitationsRoute
  '/content/': typeof ContentIndexRoute
  '/geo/': typeof GeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/compliance'
    | '/content'
    | '/credentials'
    | '/geo'
    | '/login'
    | '/opportunities'
    | '/outreach'
    | '/settings'
    | '/content/$id'
    | '/geo/citations'
    | '/content/'
    | '/geo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/compliance'
    | '/credentials'
    | '/login'
    | '/opportunities'
    | '/outreach'
    | '/settings'
    | '/content/$id'
    | '/geo/citations'
    | '/content'
    | '/geo'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/compliance'
    | '/content'
    | '/credentials'
    | '/geo'
    | '/login'
    | '/opportunities'
    | '/outreach'
    | '/settings'
    | '/content/$id'
    | '/geo/citations'
    | '/content/'
    | '/geo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ComplianceRoute: typeof ComplianceRoute
  ContentRoute: typeof ContentRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  GeoRoute: typeof GeoRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OutreachRoute: typeof OutreachRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/': {
      id: '/geo/'
      path: '/'
      fullPath: '/geo/'
      preLoaderRoute: typeof GeoIndexRouteImport
      parentRoute: typeof GeoRoute
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/geo/citations': {
      id: '/geo/citations'
      path: '/citations'
      fullPath: '/geo/citations'
      preLoaderRoute: typeof GeoCitationsRouteImport
      parentRoute: typeof GeoRoute
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
  }
}

interface ContentRouteChildren {
  ContentIdRoute: typeof ContentIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentIdRoute: ContentIdRoute,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface GeoRouteChildren {
  GeoCitationsRoute: typeof GeoCitationsRoute
  GeoIndexRoute: typeof GeoIndexRoute
}

const GeoRouteChildren: GeoRouteChildren = {
  GeoCitationsRoute: GeoCitationsRoute,
  GeoIndexRoute: GeoIndexRoute,
}

const GeoRouteWithChildren = GeoRoute._addFileChildren(GeoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ComplianceRoute: ComplianceRoute,
  ContentRoute: ContentRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  GeoRoute: GeoRouteWithChildren,
  LoginRoute: LoginRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OutreachRoute: OutreachRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
